name: Notify Google Chat on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Google Chat
        env:
          SIMARIN_PROJECT: ${{ secrets.SIMARIN_PROJECT }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New pull request: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. URL: ${{ github.event.pull_request.html_url }}"
          }' $SIMARIN_PROJECT
