name: Auto Merge to Stage Branch

on:
  push:
    branches:
      - main

jobs:
  merge_to_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge to stage branch
        run: |
          git checkout stage
          git pull origin stage
          git merge --no-ff ${{ github.sha }}
          git push origin stage
